### ISSUE TITLE
Loading data into PhiloLogic 4 seems successful, but I cannot access it through browser

### ISSUE THREAD

**Issue by nevenjovanovic** [ARTFL-Project/PhiloLogic4#411]
I have tried to install PhiloLogic 4 locally, according to instructions. XML files are being processed, but I cannot access the result with a browser. Notes on what I did and how my setup looks like are here: http://solr.ffzg.hr/dokuwiki/doku.php/z:philologic4 . Best, Neven

**Comment by rwhaling** [comment]
Hi Neven,
thanks so much for giving it a try, and for these detailed notes.  
PhiloLogic4 actually runs as an old-style CGI script, so what I think is happening is that the
SetHandler mod_python
PythonHandler mod_python.publisher
Are interfering with normal CGI Execution and normal html/js/css serving--try taking those two directives out of your configuration and try again.

Other remarks: 
The navigable_objects configuration variable refers, not to literal div1, div2 elements in your text file, but to the logical elements in PhiloLogics meta-model--that is to say, the same categories of xpath-defined elements with xpath-defined properties that are defined in the xpaths and metadata_xpaths variables, below.  An object mapped to type "div" can recur up to three layers deep, in the types called "div1", "div2", and "div3"--at the moment, "div" type objects--which would be more properly called "chunk" or "container", I suppose--are the only ones permitted to recur in this fashion.  

The navigable_objects variable, specifically, instructs the table-of-contents and navigation views which level of this hierarchy to use for primary display--for example, if you load a large encyclopedia as a single TEI file, you might wish only to navigate with div objects.

I'm happy to help you work through any issues you have with installing and configuring PhiloLogic--so let me know if this works.
::
RW

**Comment by nevenjovanovic** [comment]
Richard, thanks for the quick reply. After changes according to your suggestions, and reloading the configuration, it seems now that the dispatcher.py is run by Apache, but has problems on its line 4.

My Apache error log:

    [Sat May 23 19:34:32.514301 2015] [cgi:error] [pid 15092] [client ::1:48088] AH01215: Traceback (most recent call last):
    [Sat May 23 19:34:32.514467 2015] [cgi:error] [pid 15092] [client ::1:48088] AH01215:   File "/home/neven/public_html/philologic/proba/dispatcher.py", line 4, in <module>
    [Sat May 23 19:34:32.514549 2015] [cgi:error] [pid 15092] [client ::1:48088] AH01215:     import reports
    [Sat May 23 19:34:32.514592 2015] [cgi:error] [pid 15092] [client ::1:48088] AH01215: ImportError: No module named reports
    [Sat May 23 19:34:32.517085 2015] [cgi:error] [pid 15092] [client ::1:48088] End of script output before headers: dispatcher.py

Also documented on http://solr.ffzg.hr/dokuwiki/doku.php/z:philologic4#updatedispatcherpy_problems

**Comment by clovis** [comment]
Hi Neven,

This seems to indicate that you don't have a reports directory at the top level of your database directory. Your database directory should contain everything that is here (minus the data directory which contains the actually database data):
https://github.com/ARTFL-Project/PhiloLogic4/tree/master/www/

**Comment by nevenjovanovic** [comment]
Hello Clovis,
part of the problem were permissions on directories; I fixed this. Part of the problem seems also to be a reference to file css/philoLogic.css, which is missing in the cloned repository, and among Github files: http://github.com/ARTFL-Project/PhiloLogic4/search?utf8=%E2%9C%93&q=philoLogic.css . Perhaps it should have been built during loading the database? 

But when I try to rebuild the database (or, more precisely, to build a new one), I get the following error from load_script.py:

      chmod: cannot access '/home/neven/public_html/philologic/proba2/app/assets/css': No such file or directory
      chmod: cannot access '/home/neven/public_html/philologic/proba2/app/assets/js': No such file or directory

Documented on http://solr.ffzg.hr/dokuwiki/doku.php/z:philologic4#updatepermissions_in_philologic_proba_directory

**Comment by clovis** [comment]
Hi Neven,

So you shouldn't have to fiddle with directory permissions since PhiloLogic does that for you at load time. Some directories have very specific permissions since they need to be writable at runtime. This includes app/assets/js and app/assets/css as well as data/hitlists/.

When you access your database from the web for the first time, two files get generated, PhiloLogic.css and PhiloLogic.js. However in order for those files to be generated, app/assets/css and app/assets/js need to be writable by Apache. So the last error you mention is coming for a the fact that these two directories aren't writable. A quick fix would be to run ```chmod -R 777```on these two directories, as well as data/hitlists (without which you won't get any results for your searches). But this shouldn't be needed as this is done for you at load time.

What I would do first is make sure that the ```template_dir``` variable contained in load_script.py points to the ```www/``` directory contained in the PhiloLogic tarball. I see that you were pointing to ```/home/neven/philo4test/```. Does this directory contain the exact same thing as what was in the ```www``` directory contained in the tarball? If not, you should just make sure that it does, and make sure that the permissions are the same. 

Then, I would build the database in a different location than where your source files and load_script.py are located. This allows you to overwrite your database load without deleting your load_script and source files. 

Let me know if that helps.

**Comment by nevenjovanovic** [comment]
Clovis, thanks! I cloned the repository from Github (actually the previous time I had used the rc zip archive), checked permissions, copied the www directory elsewhere, changed the load_script.py -- now PhiloLogic 4 is working on my localhost! The full report here:
http://solr.ffzg.hr/dokuwiki/doku.php/z:philologic4#updatestart_all_over_again
Thank you both for helping!

**Comment by clovis** [comment]
Great to hear!
