### ISSUE TITLE
List authors and titles starting with accented characters in web interface

### ISSUE THREAD

**Issue by nevenjovanovic** [ARTFL-Project/PhiloLogic4#438]
In web interface, current alphabet / collation for authors and titles list does not support or display names beginning with accented characters such as Š, Č, Ž. In our test db (http://solr.ffzg.hr/philo4/croala0/) author "Škrlec" is absent from the authors list, though he can be found using "Show search options". What should I modify to make web interface use Croatian collation and display names beginning with characters with haceks?

**Comment by clovis** [comment]
Hi Neven,

The current letter range for the landing page is defined here:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/www/scripts/get_landing_page_content.py#L30

We're currently generating an ASCII alphabet which is inadequate. I think that rather than generating it programatically, we should make this configurable in the web_config.cfg file. Something along the lines of:
```
ranges = [
          [u"a", u"b", u"c", u"č", u"d"], 
          [u"e", u"f", u"g", u"h", u"i"],
          ...
         ]
```
And the code could be something like:
```
for range in config.ranges:
    if q_range in range:
        letter_range = range
        break
```

I'm marking this as a must-have for the 4.1 release. That won't happen before January however since I'm very busy with other projects.

**Comment by clovis** [comment]
This has been supported since the 4.5 release.
