### ISSUE TITLE
Unusual date formats

### ISSUE THREAD

**Issue by nevenjovanovic** [ARTFL-Project/PhiloLogic4#439]
Our texts which cannot be dated precisely get grouped by third of the century (e. g. first third of 7th century is 06xx_1_third; inspired by semium [1]; see our teiHeaders in [2]). Ours is obviously not the format expected by PhiloLogic -- but what is? Can we express thirds of century in a way PhiloLogic will understand?

[1] https://github.com/europeana/tools/blob/81d9d0cbf4e8784a44ebc9a85ed740a4b9ac0abf/europeana-enrichment-framework/enrichment/enrichment-framework-service/converters/vocabularies/tmp/backup/cacheparents.vocabularyOfTime.q-1855756949.f1252756844.txt

[2] https://github.com/nevenjovanovic/croatiae-auctores-latini-textus/tree/master/txts

**Comment by clovis** [comment]
IDates are very tricky to handle, and PhiloLogic works best when dates are integers. This is because range searches are done on the SQL side with something like:
`x >= start_date AND x <= end_date`
What problem are you running into precisely?

**Comment by nevenjovanovic** [comment]
Thanks for the reply. Actually, the 'date' field gets processed, and the search results can be sorted on it. My description was not accurate. What does not work (nothing happens when I select it) is the 'Time Series' tab; its function obviously does not expect the '16xx1_third' date description. This is quite understandable -- but still, could you give me a hint on how to adapt the time series function to my date format?

**Comment by clovis** [comment]
I'm assuming you're not getting any results because nothing is found for the date ranges you select. Both the front-end and back-end expect integers for time series. The entire time series code would have to be reworked for it support other formats.

What's going on right now is that PhiloLogic runs a regular concordance search for each time span (like 1700-1710, 1710-1720...etc), and then counts the number of hits, and reports this back to the front-end.
See here:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/www/reports/time_series.py#L45

What I suggest you do instead is to preprocess your data at load time. What you can do for that is use this script:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/extras/artfl_load_script.py

It loads another file called artfl_xpaths, which contains a list of custom xpaths (made to cover most common cases for our data) that you'll probably want to edit for your own purposes:
https://github.com/ARTFL-Project/PhiloLogic4/blob/master/extras/artfl_xpaths.py

artfl_load_script.py uses <a href="https://github.com/ARTFL-Project/PhiloLogic4/blob/master/python/philologic/Loader.py#L139">a library function</a> to pre-parse document-level metadata for sorting purposes. But since it returns all the metadata in a Python object prior to parsing the entire document (see <a href="https://github.com/ARTFL-Project/PhiloLogic4/blob/master/extras%2Fartfl_load_script.py#L140">here</a>), you can actually modify this metadata before passing it to the main parser. So in your case, you would modify the date to an integer, like the earliest date in your date range for instance. If you do want to keep the original date format, I suggest you parse the xpath twice and give the one you'll modify the name of "date", and the other something else. So in your external xpath file, you'd have something like:
`("doc", ".//profileDesc/creation/date", "date"),`
`("doc", ".//profileDesc/creation/date", "date_range"),`

I hope that helps.

**Comment by clovis** [comment]
No update on this so closing...
