### ISSUE TITLE
Loading, restart from the step : Merge parser output

### ISSUE THREAD

**Issue by glorieux-f** [ARTFL-Project/PhiloLogic4#448]
After 3 days work of a server, found in log : Mon Feb 29 17:11:11 2016: done parsing
YESSS!  BUT…
Mon Feb 29 17:11:11 2016: sorting words
Mon Feb 29 17:11:11 2016: Merging words in batches of 500...
sort: write failed: /tmp/sortMlHpbI: No space left on device

:o( the TMPDIR bug

os.environ["TMPDIR"] = "/var/www/media/tmp/" # alernative dir for big sort

Now, how to start from the step after parsing, and not wait 3 days more ?

Thanks in advance.

**Comment by clovis** [comment]
aha... there is no current way to do this... sadly... But fear not :-) we are going to be resuming work on PhiloLogic4 in a couple of weeks, and the TMPDIR bug will most certainly be fixed... The loading procedure will also be simplified (think PhiloLogic3). 

I'm keeping this bug open since restarting a load in the middle could definitely be useful for large loads.

**Comment by clovis** [comment]
The load process has changed so much, and the sorting now is cached in the database directory, so this should no longer be a problem. Loads are also much faster too.
