### ISSUE TITLE
How to upgrade from 4.5 to 4.6?

### ISSUE THREAD

**Issue by nevenjovanovic** [ARTFL-Project/PhiloLogic4#559]
A working PhiloLogic 4.5 installation is running on my system. How do I upgrade to 4.6? Do I simply run the `./install` script? Do I need to save my local modifications? (I'd rather ask than experiment.)

**Comment by clovis** [comment]
Yes, it will not overlap with the 4.5 installation since 4.6 runs under Python3 and shares the same search core as 4.5. So both versions can work simultaneously. 

Note that the 4.6 installation will only work with new database loads. Previous databases will continue running under 4.5.

You could try to convert your existing 4.5 databases to 4.6 (there's a script for that in the extras/ folder), but it takes a bit of work, more than just running the copy script, due to the string/unicode changes between Python2 and 3. Basically, all UTF-8 strings should be converted to unicode strings in both the web_config.cfg file as well as the db.locals.py file. I suggest you test this before running on a live database.
